//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intro_to_Entity_Framework.Database_First
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomsInfo
    {
        public int Id { get; set; }
        public int Area { get; set; }
        public string AccommodationAddress { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> StartRent { get; set; }
        public Nullable<System.DateTime> EndRent { get; set; }
        public Nullable<int> UsersInfoId { get; set; }
    
        public virtual UsersInfo UsersInfo { get; set; }
    }
}
